image:
  repository: keelhq/keel
  tag: latest
  pullPolicy: Always

service:
  enabled: true
  type: LoadBalancer
  externalPort: 9300
  clusterIP: ""

secret:
  create: true 

# Will be migrated to secrets but for now just hardcoding admin and password. 
# Probably would be hosting keel on 
basicauth:
  enabled: true
  user: admin
  password: password

polling:
  enabled: true
  defaultSchedule: "@every 1m"

notificationLevel: info